### ISSUE TITLE
How to use this in a HttpService?

### ISSUE THREAD

**Issue by rabejens** [ancane/haldr#1]
I can build resources with haldr which works fine. However, when I want to return them in a `HttpService`, I don't know how I have to do this.

Example:

``` scala
trait MyService extends HttpService {

  def myRoute = path("") {
    get {
      val r: Resource = ... // works
      complete(r) // <= ERROR! Cannot convert it to a ToResponseMarshallable
    }
  }
}
```

I thought of importing `HalJsonProtocol._` but this is private just to `haldr`.

So how does one correctly turn `Resource`s into JSON?

**Comment by ancane** [comment]
Hello, @rabejens. Thanks for the issue!
Can you try `import haldr._` and tell me if it works for you, please?
(`haldr` is a package object, extending `HalJsonProtocol`)

**Comment by rabejens** [comment]
When I `import haldr._` I get the above error - it cannot be converted to `ToResponseMarshallable`.

**Comment by ancane** [comment]
Sorry, didn't get it from the first time :)
Looks like you are missing `import spray.httpx.SprayJsonSupport._` from your imports.
I've put sample route here https://github.com/ancane/haldr/blob/master/src/test/scala/haldr/HaldrRouteExampleSpec.scala
